language: go

os: linux
dist: bionic
go: 1.14.x

addons:
  apt:
    packages:
      - docker-ce
branches:
  only:
    - master
env:
  global:
    - CGO_ENABLED: 0

gobuild_args: -tags=containers_image_openpgp

before_script:
  - bash build/build.sh build
  - bash .travis/travis-before.sh
  - ls -alh ${HOME}/sync/
  - ${HOME}/sync/imgsync sum ${HOME}/sync/bolt.db | wc -l
script:
  - >-
    ${HOME}/sync/imgsync sync
    --db ${HOME}/sync/bolt.db
    --push-to registry.aliyuncs.com
    --password ${PASS}
    --push-ns=k8sxio
    --user zhangguanzhang@qq.com
    --command-timeout ${TMOUT}
    --process-limit ${PROCESS:=2}
    --img-timeout ${IMG_TMOUT:=10m}
    --live-interval ${LIVE:=9m20s}
    --login-retry ${LOGIN_RETRY:=2}
    --debug=${DEBUG:=false}
    google_containers

after_success:
  - bash .travis/travis-after.sh
  - ls -alh ${HOME}/sync/
  - ${HOME}/sync/imgsync sum ${HOME}/sync/bolt.db | wc -l
after_failure:
  - bash .travis/travis-after.sh
  - ls -alh ${HOME}/sync/